- name: kubectl apply weave
  command: kubectl apply -f https://git.io/weave-kube-1.6

- name: kubectl apply dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

- name: copy manifests
  copy:
    src: "{{ role_path }}/files/manifests/"
    dest: "/home/ubuntu/manifests/"

- name: kubectl apply nginx-ingress-controller
  command: kubectl apply -f /home/ubuntu/manifests/nginx-ingress-controller.yaml
